# Site
title: "Lucy Evans"
author: "Lucy Evans"
description: "PhD researcher in bacteriophage microbiology and antimicrobial resistance."

url: "https://biolucy.co.uk"
baseurl: ""
locale: "en_GB"

# URLs
permalink: /:title/

# Markdown
markdown: kramdown
highlighter: rouge

# Moonwalk
theme_config:
  appearance: "light"
  appearance_toggle: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from generated site
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Gemfile.before-moonrise
  - _config.before-moonrise.yml
  - node_modules
  - vendor
  - _site
  - LICENSE
  - Rakefile
